<%@ Page Title="" Language="C#" MasterPageFile="~/LSR_NEW.master" AutoEventWireup="true" CodeFile="weddingList.aspx.cs" Inherits="Default2" %>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <style type="text/css">
        .style21
        {
            width: 166px;
        }
        .style22
        {
            width: 166px;
            height: 44px;
        }
        .style23
        {
            height: 44px;
        }
        .style28
        {
            width: 166px;
            height: 37px;
        }
        .style29
        {
            height: 37px;
        }
    </style>

    <asp:Panel ID="Panel1" runat="server" BackImageUrl="~/Images/Event_img/bg_images3.jpg" 
        Height="799px">
        <table style="width:100%; height: 333px;">
            <tr>
                <td class="style28">
                    &nbsp;</td>
                <td class="style29">
                    </td>
                <td class="style29">
                    </td>
            </tr>
            <tr>
                <td class="style22">
                </td>
                <td class="style23">
                    &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
                <td class="style23">
                </td>
            </tr>
            <tr>
                <td class="style21">
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style21">
                    &nbsp;</td>
                <td>
                    <asp:GridView ID="gv_weddingList" runat="server" AutoGenerateColumns="False" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        AllowPaging="True" AllowSorting="True" 
                        BackImageUrl="~/Images/Event_img/event_EDITED.jpg">

                    <Columns>

                    <asp:templatefield HeaderText="ReservationID">
                    <itemtemplate>
                    <asp:label id="lblid" runat="server" text='<%#Eval("RID")%>'>
                    </asp:label>
                    </itemtemplate> 
                    </asp:templatefield>

                    <asp:templatefield HeaderText="CustomerID">
                    <itemtemplate>
                    <asp:label id="lblid" runat="server" text='<%#Eval("custID")%>'>
                    </asp:label>
                    </itemtemplate> 
                    </asp:templatefield>

                    <asp:templatefield headertext="Date"> 
                    <itemtemplate><%#Eval("date") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("date")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>      
                    
                      <asp:templatefield headertext="Time"> 
                    <itemtemplate><%#Eval("time") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("time")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>                                  
          
                    <asp:templatefield headertext="Hotel"> 
                    <itemtemplate><%#Eval("hotelname") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("hotelname")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield> 

                    <asp:templatefield headertext="Hall"> 
                    <itemtemplate><%#Eval("hall_name") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("hall_name")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield> 

                    <asp:templatefield headertext="Theme Colour"> 
                    <itemtemplate><%#Eval("themeColor") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("themeColor")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>  

                      <asp:templatefield headertext="Decoration"> 
                    <itemtemplate><%#Eval("Decoration") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("Decoration")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>  

                      <asp:templatefield headertext="Pay Amount"> 
                    <itemtemplate><%#Eval("price") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("price")%>'>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>  



                    </Columns>
                    </asp:GridView>
                </td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style21">
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style21">
                    &nbsp;</td>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style21">
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
        </table>
    </asp:Panel>
</asp:Content>

