<%@ Page Title="" Language="C#" MasterPageFile="~/LSR_NEW.master" AutoEventWireup="true" CodeFile="weddingCustomer.aspx.cs" Inherits="Default2" %>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <style type="text/css">
        .style21
        {
            height: 109px;
        }
        .style26
        {
            height: 5px;
            width: 139px;
        }
        .style27
        {
            height: 109px;
            width: 139px;
        }
        .style28
        {
            width: 139px;
        }
        .style30
        {
            height: 5px;
        }
        .style31
        {
            height: 27px;
            width: 139px;
        }
        .style32
        {
            height: 27px;
        }
        .style33
        {
            height: 59px;
            width: 139px;
        }
        .style34
        {
            height: 59px;
            width: 921px;
        }
        .style35
        {
            height: 31px;
            width: 139px;
        }
        .style36
        {
            height: 31px;
        }
        .style37
        {
            height: 59px;
            width: 984px;
        }
        .style38
        {
            height: 31px;
            width: 984px;
        }
        .style39
        {
            height: 5px;
            width: 984px;
        }
        .style40
        {
            height: 109px;
            width: 984px;
        }
        .style41
        {
            height: 27px;
            width: 984px;
        }
        .style42
        {
            width: 984px;
        }
    </style>

    <asp:Panel ID="Panel1" runat="server" BackImageUrl="~/Images/Event_img/bg_images3.jpg" 
        Height="796px">
        <table style="width:100%; height: 371px;">
            <tr>
                <td class="style33">
                </td>
                <td class="style37">
                </td>
                <td class="style34">
                </td>
            </tr>
            <tr>
                <td class="style35">
                </td>
                <td class="style38" valign="bottom">
                    &nbsp;&nbsp;&nbsp; &nbsp;
                </td>
                <td class="style36">
                </td>
            </tr>
            <tr>
                <td class="style26">
                    &nbsp;</td>
                <td class="style39" valign="bottom">
                    &nbsp;</td>
                <td class="style30">
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style27">
                </td>
                <td class="style40">


                    <asp:Panel ID="Panel2" runat="server">
                    

                    <asp:GridView ID="gv_weddingCustomer" runat="server" 
                        onrowediting="gv_weddingCustomer_RowEditing" 
                        onrowupdating="gv_weddingCustomer_RowUpdating" 
                        onpageindexchanging="gv_weddingCustomer_PageIndexChanging" 
                        onrowcancelingedit="gv_weddingCustomer_RowCancelingEdit" 
                        onrowcommand="gv_weddingCustomer_RowCommand" 
                        onrowdeleting="gv_weddingCustomer_RowDeleting" 
                        onselectedindexchanging="gv_weddingCustomer_SelectedIndexChanging" 
                        AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        BackImageUrl="~/Images/event_EDITED.jpg" BorderColor="Black" BorderWidth="1px" 
                        ForeColor="Black" Height="364px" 
                        onselectedindexchanged="gv_weddingCustomer_SelectedIndexChanged1" 
                        Width="1089px">
                    <columns>

                    <asp:templatefield HeaderText="CustomerID">
                    <itemtemplate>
                    <asp:label id="lblid" runat="server" text='<%#Eval("CustomerID")%>'>
                    </asp:label>
                    </itemtemplate> 
                    </asp:templatefield>

                    <asp:templatefield HeaderText="Salutation">
                    <itemtemplate>
                    <asp:label id="lblid1" runat="server" text='<%#Eval("salutation")%>'>
                    </asp:label>

                    </itemtemplate> 
                    </asp:templatefield>

                    <asp:templatefield headertext="First Name"> 
                    <itemtemplate><%#Eval("fname") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox1" runat ="server" Text='<%#Eval("fname")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield> 

                    
                    <asp:templatefield headertext="Last Name"> 
                    <itemtemplate> <%#Eval("lname") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox2" runat ="server" Text='<%#Eval("lname")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="Address"> 
                    <itemtemplate> <%#Eval("state_address") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox3" runat ="server" Text='<%#Eval("state_address")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="City"> 
                     <itemtemplate> <%#Eval("city") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox4" runat ="server" Text='<%#Eval("city")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="Postal Code"> 
                    <itemtemplate> <%#Eval("PostelCode") %></itemtemplate> 
                    <editItemTemplate>
                    <asp:TextBox ID="textbox5" runat ="server" Text='<%#Eval("PostelCode")%>'>
                    </asp:TextBox>
                    </editItemTemplate> 
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="Phone"> 
                     <itemtemplate> <%#Eval("Phone") %></itemtemplate> 
                    <editItemTemplate>
                    <asp:TextBox ID="textbox6" runat ="server" Text='<%#Eval("Phone")%>'>
                    </asp:TextBox>
                    </editItemTemplate> 
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="Email"> 
                    <itemtemplate> <%#Eval("email") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox7" runat ="server" Text='<%#Eval("email")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>

                    
                    <asp:templatefield headertext="Country"> 
                    <itemtemplate> <%#Eval("Country") %></itemtemplate>  
                    <editItemTemplate>
                    <asp:TextBox ID="textbox8" runat ="server" Text='<%#Eval("country")%>'>
                    </asp:TextBox>
                    </editItemTemplate>
                    </asp:templatefield>
                           
                        <asp:templatefield headertext="Passport Number">
                            <itemtemplate>
                                <%#Eval("passport_NIC") %>
                            </itemtemplate>
                            
                            <editItemTemplate>
                                <asp:TextBox ID="textbox9" runat="server" Text='<%#Eval("passport_NIC")%>'>&#39;&gt;
                    </asp:TextBox>
                            </editItemTemplate>
                        </asp:templatefield>
                           
                    </columns>
                    </asp:GridView>
                    </asp:Panel>
                </td>
                <td class="style21">
                </td>
            </tr>
            <tr>
                <td class="style31">
                </td>
                <td class="style41">
                </td>
                <td class="style32">
                </td>
            </tr>
            <tr>
                <td class="style28">
                    &nbsp;</td>
                <td class="style42">
                    &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Label ID="lblUpdateMsg" runat="server" Text="Label" ForeColor="Red" 
                        Visible="False"></asp:Label>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Label ID="lblDeleteMsg" runat="server" Text="Label" ForeColor="Red" 
                        Visible="False"></asp:Label>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style28">
                    &nbsp;</td>
                <td class="style42">
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
        </table>
    </asp:Panel>
</asp:Content>

